import type { Metadata } from "next";
import type { LayoutProps } from "@/types";
import "@fontsource-variable/outfit";
import "@/app/globals.css";
import { Navigation } from "@/components/Navigation";
import { Toaster } from "@/components/ui/sonner";

const title = "Create Next App";
const description = "Generated by create next app";
export const metadata: Metadata = {
  title: {
    template: `%s | ${title}`,
    default: title,
  },
  description,
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="ja">
      <body>
        <div className="min-h-screen">
          <Navigation />
          <main>{children}</main>

          <div
            id="dummy-block"
            className="mt-48 h-48 sticky top-full bg-slate-200 text-slate-800 text-2xl font-bold grid place-items-center"
          >
            Dummy block
          </div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
