import type { Metadata } from "next";
import type { LayoutProps } from "@/types";
import "@/app/globals.css";

const title = "Create Next App";
const description = "Generated by create next app";
export const metadata: Metadata = {
  title: {
    template: `%s | ${title}`,
    default: title,
  },
  description,
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="ja">
      <body>
        <div className="min-h-screen">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
