import type { Metadata } from "next";
import type { LayoutProps } from "@/types";
import "@fontsource-variable/outfit";
import "@/app/globals.css";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

const title = "Create Next App";
const description = "Generated by create next app";
export const metadata: Metadata = {
  title: {
    template: `%s | ${title}`,
    default: title,
  },
  description,
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="ja">
      <body>
        <div className="min-h-screen">
          <Navigation />

          <main>{children}</main>

          <Footer className="mt-24 sticky top-full" />
        </div>

        <Toaster />
      </body>
    </html>
  );
}
